### ISSUE TITLE
Disable annoying sound

### ISSUE THREAD

**Issue by ADMINKS1** [sp-wahl/wahlstand#7]
Hey, your work is great!
Could you please tell me how to diable the annoyingly changing background colors and the music?

**Comment by HSZemi** [comment]
Honestly, no idea where it even came from. It haunts us every year 😶

**Comment by ADMINKSE** [comment]
But do you know how you play this sound? That way, I might find it in the code

**Comment by timracs** [comment]
Do you mean temporarily? Pressing any button should do this.
Or do you mean permanently? If so, I would recommend that you take a look at the ["Add Funk" commit](https://github.com/sp-wahl/wahlstand/commit/d0e95360c0635d1c2b513b4ed6e3eccc14c892a3) (without having done this myself).

**Comment by ADMINKS1** [comment]
Deleting the funk.js worked, thank you
